main/urls.py
from django.conf.urls import url
from main import views

urlpatterns = [
	url(r'^$', views.login, name="login"),
	url(r'logout/$', views.logout ,name="logout")
]

war_demolay/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static

# responsável pelo redirecionamento caso o usuário tente visualizar uma página que seja nencessário realizar login
from django.contrib.auth.views import login

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^avaliador/', include("avaliador.urls")),
    url(r'^', include("main.urls", namespace="main")),
    url(r'^capitulo/', include("capitulo.urls")),
    url(r'^territorio/', include("mapa.urls")),
    url(r'^inicio/', include('inicio.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

main/models.py
from django.db import models
from django.contrib.auth.models import User

class Contato(models.Model):
	class Meta:
		db_table = "contato" #isso define o nome da tabela no banco

	usuario = models.ForeignKey(User)
	contato = models.CharField(max_length=128)

main/forms.py
from django import forms
from avaliador.models import Gabinete_User

class LoginForm(forms.Form):
	login = forms.CharField(label="login", max_length=50, 
		widget=forms.TextInput(attrs={
			"class":"form-control", 
			"placeholder": "Digite aqui seu login",
			"id":"usuario"}))
	senha = forms.CharField(label='senha', max_length=50, 
		widget=forms.PasswordInput(attrs={
			"class":"form-control", 
			"placeholder": "Digite aqui sua senha",
			"id":"senha"}))

main/views.py
from django.contrib.auth.models import User
from django.shortcuts import render
from main.forms import LoginForm
from django.contrib.auth import authenticate
from django.contrib.auth import login as login_authenticate
from django.contrib.auth import logout as logout_request
from django.http import HttpResponseRedirect
from avaliador.models import Gabinete_User
from capitulo.models import Capitulo_User

LIST_MODELS_AUTH = [[Gabinete_User, "/avaliador/home/"],
					[Capitulo_User, "/capitulo/home"]]

# Create your views here.
def login(request):
	if request.method == "POST":		
		form = LoginForm(request.POST)
		
		if form.is_valid():
			form_login = form.cleaned_data["login"]
			form_senha = form.cleaned_data["senha"]
			teste = User.objects.get(username=form_login)
			print(teste.first_name)
			user = authenticate(username=form_login, password=form_senha)

			if(user is not None):
				login_authenticate(request, user)
				redirect_url = redirect(request)
				if redirect_url != None:
					url_redirect_auth = request.GET.get("next", redirect_url)
					return HttpResponseRedirect(url_redirect_auth)

				context = {"error": True, 
				"msg_error": "Nenhum usuário cadastro no sistema!", 
				"form": form}
				return render(request, "main/login.html", context=context)
			else:
				context = {"error": True, 
				"msg_error": "Login/senha incorretos!", 
				"form": form}
				return render(request, "main/login.html", context=context)
	form = LoginForm()
	param = request.GET.get("next", None)
	login_required =  param != None
	context = {"url_redirect": param ,"form":form, "error":login_required, "msg_error": "É necessário realizar login para acessar a página solicitada!"}

	return render(request, "main/login.html", context=context)

def logout(request):
	logout_request(request)
	return HttpResponseRedirect("/inicio/mapa")

def redirect(request):
	for models in LIST_MODELS_AUTH:
		try:
			models[0].objects.get(user_id=request.user.id)
			return models[1]
		except models[0].DoesNotExist:
			pass
	return None

templates/main/login.html
<!DOCTYPE html>
{% load staticfiles %}
<html>
<head>
	<title>War DeMolay - Login</title>
	<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
	<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
	<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>

	<link rel="stylesheet" href="https://www.w3schools.com/w3css/4/w3.css">
	<link rel="stylesheet" href="{% static "css/login.css" %}">

	<meta charset="utf-8">

</head>
<body   background = "static/imagens/war_dm_fundo.jpg" style="background-repeat: no-repeat; background-size: 100% " >
	<div class="container-fluid">
		<div id="conteudo" class="row">
			<div class="col-sm-4 col-md-4 col-lg-4 col-xl-4"></div>

			<div class="col-sm-4 col-md-4 col-lg-4 col-xl-4">
				<div class="w3-card-4" id = "fundo_login" >
					<img id="avatar" src="{% static "imagens/avatar-demolay.png" %}?next={{url_redirect}}" class="img-circle" alt="Avatar DeMolay">

				  	<div class="w3-container w3-center">
				    	<form action="{% url 'main:login' %}" method="POST">
				    		{%csrf_token%}
				    		<div class="form-group">
				    			{{form.login}}
				    		</div>
				    		<div class="form-group">
				    			{{form.senha}}
				    		</div>  
				    		<button id="button_submit" class="btn btn-info" type="submit">Entrar</button>

				    		{%if error == True%}
				    			<div id="alerta" class="alert alert-danger">
				    			{{msg_error}}
				    			</div>
				    		{%endif%}
				    	</form>
				  	</div>
				</div>
			</div>
		
		<div class="col-sm-4 col-md-4 col-lg-4 col-xl-4"></div>		
		<footer>Copyright © 2016 | <cite title="Título da fonte">GCE-PB, Gabinete Estadual da Paraíba</cite></footer>		
	</div>
</body>
</html>

templates/main/teste.html
<DOCTYPE html>
<html>
<head>
    <style type="text/css">
    body{margin:0; padding:0}
    #canvasMapa{width:100%; height:100%; border: solid 1px}
    </style>
    <script type="text/javascript">
    window.onload = function(){
        var canvas = document.getElementById("canvasMapa");
        var context = canvas.getContext("2d");             
        var tile = new Image();
        tile.onload = function(){
            var i, j;                      
            for(i=0; i < canvas.height/tile.height; i++){
                for(j = 0; j < canvas.width/tile.width; j++){    
                    context.drawImage(tile, i*tile.height, j*tile.width);
                }
            }                  
        };
            grama.src = "grama.png";
    };
    </script>
</head>
<body>
<canvas id="canvasMapa"></canvas>
</body>
</html>


Read more: http://www.linhadecodigo.com.br/artigo/3582/html-e-javascript-desenhando-um-mapa-2d.aspx#ixzz4v8Ff8Eor