main/urls.py
from django.conf.urls import url
from main import views

urlpatterns = [
	url(r'^$', views.login, name="login"),
	url(r'logout/$', views.logout ,name="logout")
]

war_demolay/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static

# responsável pelo redirecionamento caso o usuário tente visualizar uma página que seja nencessário realizar login
from django.contrib.auth.views import login

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^avaliador/', include("avaliador.urls")),
    url(r'^', include("main.urls", namespace="main")),
    url(r'^capitulo/', include("capitulo.urls")),
    url(r'^territorio/', include("mapa.urls")),
    url(r'^inicio/', include('inicio.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

templates/acesso_negado.html
<!DOCTYPE html>
<html>
<title>W3.CSS</title>
<meta name="viewport" content="width=device-width, initial-scale=1">
<link rel="stylesheet" href="https://www.w3schools.com/w3css/4/w3.css">
<body>

<div class="w3-container w3-center" style="margin-top:10px">
  <div class="w3-card-4">
    <header class="w3-container w3-orange">
      <h1>Acesso restrito!</h1>
    </header>

    <div class="w3-container">
      <p>Você não tem permissão para acessar a URL: <strong> {{url}}</strong></p>
    </div>

    <footer class="w3-container w3-orange">
      <h5 url_redirect="{{url_redirect}}" id="cronometro">Redirecionamento em ...</h5>
      <a style="margin-bottom: 10px" class="w3-btn w3-green" href="{{url_redirect}}">Redirecionar agora</a>
    </footer>
  </div>
</div>

  <script>
      var i = 4; // segundos
      function contagemRegressiva(){
      if(i == 0){
        window.location= window.location.protocol + "//" + window.location.host + document.getElementById("cronometro").getAttribute("url_redirect");
      }else{
        i--;
        var cronometro =  document.getElementById('cronometro');
        cronometro.innerHTML = "Redirecionamento em " + i + " ...";
      }
      }
      setInterval("contagemRegressiva()", 1000);
  </script>

</body>
</html>

templates/base_avaliador.html
<!DOCTYPE html>
{% load staticfiles%}
<html>
<title>War DeMolay - Gerencia</title>
<meta charset="UTF-8">
<link rel="stylesheet" href="{% static "css/w3-v4.css" %}">
<link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Raleway">
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
<link rel="stylesheet" type="text/css" href="{% static "css/base_html_gerente.css" %}">

{% block assets%}
{% endblock%}

<body class="w3-light-grey">

<!-- Top container -->

<div id="top-container" class="w3-bar w3-top w3-black w3-large" style="z-index:4">
  <button class="w3-bar-item w3-button w3-hide-large w3-hover-none w3-hover-text-light-grey" onclick="w3_open();"><i class="fa fa-bars"></i>  Menu</button>
  <a id="link" href="{% url "main:logout" %}" class="w3-bar-item w3-right w3-hover-blue"><i class="fa fa-sign-out"></i> Logout</a>
  <span class="w3-bar-item w3-left"><strong>War DM</strong></span>
  <a id="link" href="{% url "avaliador_home" %}" class="w3-bar-item w3-left w3-hover-blue"><i class="fa fa-home"></i> Inicio</a>
  <a id="link" href="{% url 'mapa' %}" class="w3-bar-item w3-left w3-hover-blue"><i class="fa fa-map-marker"></i> Mapa Geral</a>

</div>
<!-- Sidebar/menu -->
<nav class="w3-sidebar w3-collapse w3-white" id="mySidebar"><br>
  <div class="w3-container w3-row">
    <div class="w3-col s4">
      <img id="foto-perfil" src="{{corretor.foto.url}}" class="w3-circle w3-margin-right">
    </div>
    <div class="w3-col s8 w3-bar">
      <span>Bem-vindo, <strong>{{user.first_name}} </strong></span>
        <div class="w3-dropdown-hover w3-right fa fa-cog w3-margin-right" style="margin-top:5px; ">
               <div style="right:0;" class="w3-dropdown-content w3-bar-block w3-card-4">
                   <a href="{% url "profile_edit"%}" class="fa fa-address-card-o w3-bar-item w3-button w3-hover-red"> Editar Perfil</a><hr
                       style="margin:0px">
                   <a href="{% url 'password_edit' %}" class="fa fa-key w3-bar-item w3-button w3-hover-red"> Alterar Senha</a>
               </div>
           </div>
      <span style="display: block;">{{corretor.tipo_usuario}} - PB</span>
    </div>
  </div>
  <hr>

  <div class="w3-container">
    <h5>Capítulos</h5>
  </div>
  <div class="w3-bar-block">
    {% block capitulos%}
    {% endblock%}
    {% for capitulo in capitulos%}

      {%if capitulo.2 == True%}
        <a href="{% url "cap_numero" capitulo.0.numero %}" class="w3-hover-red w3-bar-item w3-button w3-padding"><i class="fa fa-home fa-fw"></i>  {{capitulo.0.user.first_name}}
        {% if capitulo.1 == 0%}

        {%elif capitulo.1 < 5%}
          <span class="w3-badge w3-green">{{capitulo.1}}</span>
        {% elif capitulo.1 < 10%}
          <span class="w3-badge w3-orange">{{capitulo.1}}</span>
        {%else %}
          <span class="w3-badge w3-red">{{capitulo.1}}</span>
        {%endif%}
        </a>

      {%else%}  
        <a href="{% url "mapa_cap" capitulo.0.numero %}" class="w3-hover-red w3-bar-item w3-button w3-padding"><i class="fa fa-home fa-fw"></i>  {{capitulo.0.user.first_name}}</a>
      {%endif%}   
    {% endfor %}
  </div>

</nav>


<!-- efeito de escurecimento da tela quando ficar responsiva-->
<div class="w3-overlay w3-hide-large w3-animate-opacity" onclick="w3_close()" style="cursor:pointer" title="close side menu" id="myOverlay"></div>

<!-- !PAGE CONTENT! -->
<div class="w3-main">

  <!-- Header -->
  <br>
  {% block conteudo %}

  {% endblock %}

  

</div>
  <!-- End page content -->

<script src="{% static "js/base_html_gerente.js" %}"></script>
</body>
</html>
<!-- fechamento do html-->

templates/base_capitulo.html
<!DOCTYPE html>
{% load staticfiles%}
<html>
<title>War DeMolay - Gerencia</title>
<meta charset="UTF-8">
<link rel="stylesheet" href="{% static "css/w3-v4.css" %}">
<link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Raleway">
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
<link rel="stylesheet" type="text/css" href="{% static "css/base_html_gerente.css" %}">

{% block assets%}
{% endblock%}

<body class="w3-light-grey">

<!-- Top container -->

<div id="top-container" class="w3-bar w3-top w3-black w3-large" style="z-index:4">
  <button class="w3-bar-item w3-button w3-hide-large w3-hover-none w3-hover-text-light-grey" onclick="w3_open();"><i class="fa fa-bars"></i>  Menu</button>
    <a id="link" href="{% url "main:logout" %}" class="w3-bar-item w3-right w3-hover-blue"><i class="fa fa-sign-out"></i> Logout</a>
    <span class="w3-bar-item w3-left"><strong>War DM</strong></span>
    <a id="link" href={% url 'capituloHome'%} class="w3-bar-item w3-left w3-hover-blue"><i class="fa fa-home"></i> Inicio</a>
    <a id="link" href="{% url "cap_relatorios" %}" class="w3-bar-item w3-left w3-hover-blue"><i class="fa fa-book"></i> Meus relatório</a>
    <a id="link" href="{% url "mapa_geral_capitulo" %}" class="w3-bar-item w3-left w3-hover-blue"><i class="fa fa-map-marker"></i> Mapa geral</a>
    <a id="link" href="{% url "regras" %}" class="w3-bar-item w3-left w3-hover-blue"><i class="fa fa-wpforms"></i> Regras</a>
    <a id="link" href="{% url "avaliadores_capitulo" %}" class="w3-bar-item w3-left w3-hover-blue"><i class="fa fa-user"></i> Avaliadores</a>

  <!--
  <a id="link" href="{% url "password_edit" %}" class="w3-bar-item w3-left w3-hover-blue"><i class="fa fa-key"></i> Editar Senha</a>
  -->
</div>

<!-- Sidebar/menu -->
<nav class="w3-sidebar w3-collapse w3-white" id="mySidebar"><br>
  <div class="w3-container w3-row">
    <div class="w3-col s4">
        <img id="foto-perfil" src="{{ capitulo.foto.url }}" class="w3-circle w3-margin-right">

    </div>
    <div class="w3-col s8 w3-bar">
      <span>Bem-vindo, <strong>{{capitulo.mestre_conselheiro}} </strong></span>
         <div class="w3-dropdown-hover w3-right fa fa-cog">
                <div style="right:0;" class="w3-dropdown-content w3-bar-block w3-card-4">
                    <a href="{% url "editar_cap"%}" class="fa fa-address-card-o w3-bar-item w3-button w3-hover-red"> Alterar dados</a><hr
                        style="margin:0px">
                    <a href="{% url 'edit_senha' %}" class="fa fa-key w3-bar-item w3-button w3-hover-red"> Alterar senha</a>
                </div>
            </div>

      <span style="display: block;">Região: {{ capitulo.regiao}} </span>
    </div>
  </div>
  <hr>

  <div class="w3-container">
    <h5 ><b>Capítulos</b></h5>
  </div>
    <div class="w3-bar-block">
    {% for capitulo in capitulos %}
        <a href="{% url 'mapa_cap_individual' capitulo.numero %}" class="w3-hover-red w3-bar-item w3-button w3-padding"><i class="fa fa-home fa-fw"></i>  {{capitulo.user.first_name}}</a>
    {% endfor %}
    </div>
    <!--
    <a href="#" class="w3-bar-item w3-button w3-padding w3-blue"><i class="fa fa-home fa-fw"></i>  Filhos do Imperador <span class="w3-badge w3-green">1</span></a>
    <a href="#" class="w3-bar-item w3-button w3-padding"><i class="fa fa-home fa-fw"></i>  Defensores do Rio Vermelho <span class="w3-badge w3-red">8</span></a>
    <a href="#" class="w3-bar-item w3-button w3-padding"><i class="fa fa-home fa-fw"></i>  Deus, pátria e familia <span class="w3-badge w3-orange">5</span></a>
    <a href="#" class="w3-bar-item w3-button w3-padding"><i class="fa fa-home fa-fw"></i>  João Pessoa <span class="w3-badge w3-green">2</span></a>
    -->
  </div>

</nav>


<!-- efeito de escurecimento da tela quando ficar responsiva-->
<div class="w3-overlay w3-hide-large w3-animate-opacity" onclick="w3_close()" style="cursor:pointer" title="close side menu" id="myOverlay"></div>

<!-- !PAGE CONTENT! -->
<div class="w3-main">

  <!-- Header -->
  <br>
  {% block conteudo %}

  {% endblock %}



</div>
  <!-- End page content -->

<script src="{% static "js/base_html_gerente.js" %}"></script>
</body>
</html>
<!-- fechamento do html-->

templates/base_gerente.html
<!DOCTYPE html>
{% load staticfiles%}
<html>
<title>War DeMolay - Gerencia</title>
<meta charset="UTF-8">
<link rel="stylesheet" href="{% static "css/w3-v4.css" %}">
<link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Raleway">
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
<link rel="stylesheet" type="text/css" href="{% static "css/base_html_gerente.css" %}">

{% block assets%}
{% endblock%}

<body class="w3-light-grey">

<!-- Top container -->
<div id="top-container" class="w3-bar w3-top w3-black w3-large" style="z-index:4">
  <button class="w3-bar-item w3-button w3-hide-large w3-hover-none w3-hover-text-light-grey" onclick="w3_open();"><i class="fa fa-bars"></i>  Menu</button>
  <a id="link" href="#" class="w3-bar-item w3-right w3-hover-blue"><i class="fa fa-sign-out"></i> Logout</a>
  <span class="w3-bar-item w3-left"><strong>War DM</strong></span>
  <a id="link" href="#" class="w3-bar-item w3-left w3-hover-blue"><i class="fa fa-home"></i> Inicio</a>
  <a id="link" href="{% url "cadastroCapitulo" %}" class="w3-bar-item w3-left w3-hover-blue"><i class="fa fa-plus-circle"></i> Cadastrar Capítulo</a>
  <a id="link" href="{% url "cadastro_avaliador" %}" class="w3-bar-item w3-left w3-hover-blue"><i class="fa fa-plus-circle"></i> Cadastrar Avaliador</a>
</div>

<!-- Sidebar/menu -->
<nav class="w3-sidebar w3-collapse w3-white" id="mySidebar"><br>
  <div class="w3-container w3-row">
    <div class="w3-col s4">
      <img id="foto-perfil" src="{% static "imagens/avatar-demolay.png" %}" class="w3-circle w3-margin-right">
    </div>
    <div class="w3-col s8 w3-bar">
      <span>Bem-vindo, <strong>Sr. Neto </strong><a href="#"><i class="fa fa-cog"></i></a></span>
      
      <span style="display: block;">MCA - PB</span>
    </div>
  </div>
  <hr>
    <div class="w3-container opcoes-sidebar">
      <div class="w3-dropdown-click">
        <button onclick="controleDropdown('dropdown1')" class="w3-button w3-white btn-sidebar"><h5>Avaliadores <i class="fa fa-caret-square-o-down"></i></h5></button>
        <div id="dropdown1" class="w3-bar-block w3-dropdown-content w3-bar-block w3-card-4 w3-animate-zoom">
          <a href="#" class="w3-bar-item w3-button w3-padding w3-blue"><i class="fa fa-male fa-fw"></i>  Vitor Pereira - 1º Região</a>
          <a href="#" class="w3-bar-item w3-button w3-padding"><i class="fa fa-male fa-fw"></i>  Eduardo Gouveia - 2º Região</a>
        </div>
      </div>
    </div>

  <hr>
    <div class="w3-container opcoes-sidebar">
      <div class="w3-dropdown-click">
        <button onclick="controleDropdown('dropdown2')" class="w3-button w3-white btn-sidebar"><h5>Capítulos <i class="fa fa-caret-square-o-down"></i></h5></button>
        <div id="dropdown2" class="w3-bar-block w3-dropdown-content w3-bar-block w3-card-4 w3-animate-zoom">
          <a href="#" class="w3-bar-item w3-button w3-padding w3-blue"><i class="fa fa-globe"></i> Listar Todos</a>

          <a href="#" class="w3-bar-item w3-button w3-padding"><i class="fa fa-home fa-fw"></i>  Filhos do Imperador <span class="w3-badge w3-green">1</span></a>
          <a href="#" class="w3-bar-item w3-button w3-padding"><i class="fa fa-home fa-fw"></i>  Defensores do Rio Vermelho <span class="w3-badge w3-red">8</span></a>
          <a href="#" class="w3-bar-item w3-button w3-padding"><i class="fa fa-home fa-fw"></i>  Deus, pátria e familia <span class="w3-badge w3-orange">5</span></a>
          <a href="#" class="w3-bar-item w3-button w3-padding"><i class="fa fa-home fa-fw"></i>  João Pessoa <span class="w3-badge w3-green">2</span></a>

        </div>
       </div>
    </div>

  <!--
  <div class="w3-container">
    <h5>Capítulos</h5>
  </div>
  <div class="w3-bar-block">
    
    <a href="#" class="w3-bar-item w3-button w3-padding w3-blue"><i class="fa fa-home fa-fw"></i>  Filhos do Imperador <span class="w3-badge w3-green">1</span></a>
    <a href="#" class="w3-bar-item w3-button w3-padding"><i class="fa fa-home fa-fw"></i>  Defensores do Rio Vermelho <span class="w3-badge w3-red">8</span></a>
    <a href="#" class="w3-bar-item w3-button w3-padding"><i class="fa fa-home fa-fw"></i>  Deus, pátria e familia <span class="w3-badge w3-orange">5</span></a>
    <a href="#" class="w3-bar-item w3-button w3-padding"><i class="fa fa-home fa-fw"></i>  João Pessoa <span class="w3-badge w3-green">2</span></a>
  </div>
  -->
</nav>


<!-- efeito de escurecimento da tela quando ficar responsiva-->
<div class="w3-overlay w3-hide-large w3-animate-opacity" onclick="w3_close()" style="cursor:pointer" title="close side menu" id="myOverlay"></div>

<!-- !PAGE CONTENT! -->
<div class="w3-main">

  <!-- Header -->
  <br>
  {% block conteudo %}

  {% endblock %}

  

</div>
  <!-- End page content -->

<script src="{% static "js/base_html_gerente.js" %}"></script>
</body>
</html>

templates/base_home.html
{% load staticfiles %}
<!DOCTYPE html>
<html>
<head>
	<title>War DeMolay - Mapa Geral</title>
	<meta charset="UTF-8">
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<link rel="stylesheet" href="https://www.w3schools.com/w3css/4/w3.css">
	<link rel="stylesheet" href="https://www.w3schools.com/lib/w3-theme-black.css">
	<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
  <link rel="stylesheet" href="{% static "css/base_html_home.css" %}">
  <!--<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>-->
  <script src="http://ajax.googleapis.com/ajax/libs/jquery/1.7.1/jquery.min.js" type="text/javascript">
  </script> 
  <script src="https://ajax.googleapis.com/ajax/libs/jqueryui/1.8.16/jquery-ui.min.js" type="text/javascript"></script>
  <link rel="stylesheet" href="http://code.jquery.com/ui/1.8.18/themes/base/jquery-ui.css" type="text/css" media="all" />


  <script>
    function getCookie(c_name)
    {
        if (document.cookie.length > 0)
        {
            c_start = document.cookie.indexOf(c_name + "=");
            if (c_start != -1)
            {
                c_start = c_start + c_name.length + 1;
                c_end = document.cookie.indexOf(";", c_start);
                if (c_end == -1) c_end = document.cookie.length;
                return unescape(document.cookie.substring(c_start,c_end));
            }
        }
        return "";
     }


    function login(){
      var username = document.getElementById("username").value;
      var passwd = document.getElementById("passwd").value;
      $.ajax({
        url: "/inicio/login/",
        type: 'POST',
        dataType: 'json',
        data: {"username": username, "passwd": passwd},
        headers: { "X-CSRFToken": getCookie("csrftoken")}
      })
      .done(function(data) {
        console.log("success");
        console.log(data)
        if (data["sucesso"]){
          window.location.href = data["url_redirect"];
        }else{
          var msg_erro = document.getElementById("msg_erro");
          msg_erro.style.display = "block";
          msg_erro.innerText = data["msg_error"];
        }
        
      })
      .fail(function() {
        console.log("error");
      })
      .always(function() {
        console.log("complete");
      });
    }
  
  </script>

  <script>
    $(function() {
      $("#pesquisa_cap").autocomplete({
        source: "/inicio/autocomplete/",
        minLength: 2,
        select: function (event, object) {
                //alert('You selected: ' + object.item.id);
                window.location.href = "/inicio/cap/" + object.item.id + "/mapa/";
            }
      });
    });
  </script>

      
<!--CSS DO INPUT DE BUSCA!-->

{%block assets%}
{%endblock assets%}

</head>
  <body>

    <img id="fundo_batalha" src="{% static "imagens/img_fundo_batalha.jpg" %}" style="width: 100%; height: 100%; position: absolute; top:0; left: 0; z-index: 0;">

    <div id="content" class="w3-row " style=" width: 100%; height: 100%; position: absolute; top: 0; left: 0; z-index: 1;
    overflow: auto;"><!--conteiner principal!-->


      <div class="w3-col l2 m6 s4 w3-gray-ligth w3-center"><!--container da barra lateral esquerda!--><p></p></div><!--final do conteiner da barra lateral esquerda!-->


      <div id="principal" class=" w3-col l8 m6 s4 " style="margin-top: 100px; border-radius: 6px; "><!--container central!-->


      <!--Barra de navegação!-->

        <a href="#" class="w3-bar-item w3-button  w3-hover-black" style="color: white;"><i class="fa fa-home w3-margin-right" ></i><strong>Inicio</strong></a>
        <a href="{% url "mapa_inicio" %}" class="w3-bar-item w3-button w3-hover-black" style="color: white;"><strong>Mapa</strong></a>
        <a href="{% url "avaliadores" %}" class="w3-bar-item w3-button  w3-hover-black" style="color: white;"><strong>Avaliadores</strong></a>
        <a href="{% url "regras_inicio" %}" class="w3-bar-item w3-button  w3-hover-black" style="color: white;"><strong>Regras</strong></a>
        <a href="{%url "edicoes"%}" class="w3-bar-item w3-button  w3-hover-black" style="color: white;"><strong>Edições Anteriores</strong></a>
        <button onclick="document.getElementById('id01').style.display='block'" class="w3-bar-item w3-button  w3-hover-black" style="float: right; color: white;"> <strong>Login</strong> </button>
        <div id="id01" class="w3-modal">
          <div class="w3-modal-content w3-card-4 w3-animate-zoom" style="max-width:400px">
            <div class="w3-center"><br>
              <span onclick="document.getElementById('id01').style.display='none'" class="w3-button w3-xlarge w3-transparent w3-hover-red w3-display-topright" title="Close Modal">×</span>
              <img  src="/static/imagens/avatar-demolay.png" alt="Avatar" style="width:25%; background-color: white;" class="w3-circle w3-margin-top">
            </div>


            <div class="w3-container w3-center" style="margin-top: 20px;">

              <form id="form_login" onsubmit="event.preventDefault(); login();" class="w3-container">
                <div class="w3-section">
                  <input id="username" required="true" class="w3-input w3-border w3-margin-bottom" placeholder="Usuário" style="border-radius: 4px;">
                  <input id="passwd" required="true" class="w3-input w3-border" type="password" placeholder="Senha" style="border-radius: 4px;">
                  <button class="w3-button w3-block w3-green w3-section w3-padding" type="submit" style="border-radius: 4px;">Entrar</button>
                </div>
              </form>
              <label id="msg_erro" class="w3-text-red" style="display:none"></label>
            </div>

            <div class="w3-container w3-border-top w3-padding-16 w3-light-grey">
              <button onclick="document.getElementById('id01').style.display='none'" type="button" class="w3-button w3-red" style="border-radius: 4px;">Cancelar</button>
              <span class="w3-right w3-padding w3-hide-small">Esqueceu a <a href="#">senha?</a></span>
            </div>
          </div>
        </div>



      <!--Final da barra de navegação!-->


        <div id="main_template_base" style="background-color: #721919"> <!--Conteúdo!-->

          
          <input id="pesquisa_cap" type="text" name="search" placeholder="Buscar capítulo" ><button class="w3-button w3-white  w3-hover-black" style="border-radius: 4px; margin-bottom: 4px; margin-left: 1px"><i class="fa fa-search"></i></button>

          

          {% block conteudo %}
          {% endblock %}
        </div><!--Final do Conteúdo!-->



      </div><!--final do conteiner central!-->

      <div class="w3-col l2 m3 s4 w3-gray-ligth w3-center"><!--conteiner da barra lateral direita!--></div><!--final do conteiner da barra lateral direita!-->
    </div>



  </body>
</html>